/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    courses: Course;
    pages: Page;
    'knowledge-base': KnowledgeBase;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'knowledge-base': KnowledgeBaseSelect<false> | KnowledgeBaseSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    contacts: Contact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Unique key for mapping (e.g. estimateService)
   */
  key: string;
  title: string;
  description?: string | null;
  /**
   * URL slug (e.g. smetnoe-obsluzhivanie)
   */
  slug: string;
  content?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Meta title (если не задан — используется title)
   */
  metaTitle?: string | null;
  /**
   * Meta description
   */
  metaDescription?: string | null;
  /**
   * OG изображение (рекомендуется 1200×630 px)
   */
  ogImage?: (number | null) | Media;
  hasTariffs?: boolean | null;
  tariffItems?:
    | {
        name: string;
        price: string;
        description?: string | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Display order on training page (lower = first)
   */
  order?: number | null;
  /**
   * Unique key (e.g. express-course, contract-price)
   */
  key: string;
  title: string;
  duration?: string | null;
  price?: string | null;
  slug: string;
  topics?:
    | {
        topic?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Meta title (если не задан — используется title)
   */
  metaTitle?: string | null;
  /**
   * Meta description
   */
  metaDescription?: string | null;
  /**
   * OG изображение (рекомендуется 1200×630 px)
   */
  ogImage?: (number | null) | Media;
  programSections?:
    | {
        title: string;
        content?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path (e.g. home, about-us). Use "home" for the main page. Not: services, training, contacts (reserved).
   */
  slug: string;
  /**
   * Show this page in header/footer navigation
   */
  showInNav?: boolean | null;
  /**
   * Order in navigation (lower = first)
   */
  navOrder?: number | null;
  /**
   * Page meta title
   */
  metaTitle?: string | null;
  /**
   * Page meta description
   */
  metaDescription?: string | null;
  /**
   * OG изображение для этой страницы (рекомендуется 1200×630 px)
   */
  ogImage?: (number | null) | Media;
  layout?:
    | (
        | {
            /**
             * Small badge above title (e.g. Сметные услуги · Минск · РБ)
             */
            badge?: string | null;
            title: string;
            subtitle?: string | null;
            cta?: string | null;
            /**
             * URL for CTA button
             */
            ctaLink?: string | null;
            secondaryCta?: string | null;
            /**
             * URL for secondary button
             */
            secondaryCtaLink?: string | null;
            background?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'badge';
          }
        | {
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            /**
             * Optional section heading (h2)
             */
            title?: string | null;
            paragraphs: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'seoParagraphs';
          }
        | {
            title: string;
            /**
             * Optional image
             */
            image?: (number | null) | Media;
            /**
             * Or use static path: /images/filename.png
             */
            imageUrl?: string | null;
            /**
             * Optional link URL (e.g. https://belsmeta.by)
             */
            linkUrl?: string | null;
            /**
             * Link text
             */
            linkText?: string | null;
            paragraphs: {
              text: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Small tag above title (e.g. Услуги)
             */
            sectionTag?: string | null;
            /**
             * Section heading
             */
            sectionTitle?: string | null;
            /**
             * Subtitle/description below title
             */
            sectionSubtitle?: string | null;
            /**
             * Max services to show (0 = all)
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceList';
          }
        | {
            /**
             * Small tag (e.g. Обучение)
             */
            sectionTag?: string | null;
            sectionTitle?: string | null;
            sectionSubtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'courseList';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            /**
             * Tag for CTA section (e.g. Контакты)
             */
            sectionTag?: string | null;
            /**
             * Title for CTA+form section
             */
            sectionTitle?: string | null;
            /**
             * Description text
             */
            sectionDescription?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            /**
             * Small tag above title (e.g. Принципы работы)
             */
            sectionTag?: string | null;
            /**
             * Section heading (e.g. Our principles of work)
             */
            sectionTitle: string;
            items: {
              /**
               * Icon for the principle card
               */
              icon: 'speed' | 'accuracy' | 'honesty' | 'fixedPrice';
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'principles';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'consultationForm';
          }
        | {
            /**
             * Small tag above title (e.g. Преимущества)
             */
            tag?: string | null;
            title: string;
            description?: string | null;
            ctaText?: string | null;
            items: {
              icon: 'check' | 'shield' | 'clock' | 'dollar';
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages';
          }
        | {
            /**
             * Small tag (e.g. Тарифы)
             */
            sectionTag?: string | null;
            sectionTitle?: string | null;
            sectionDescription?: string | null;
            cards: {
              title: string;
              description?: string | null;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              ctaText?: string | null;
              isFeatured?: boolean | null;
              featuredBadge?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            /**
             * Small tag (e.g. База знаний)
             */
            tag?: string | null;
            title: string;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            articlesTitle?: string | null;
            articleSource?: ('featured' | 'manual') | null;
            manualSlugs?:
              | {
                  slug: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'knowledge';
          }
        | {
            /**
             * Small tag (e.g. О специалисте)
             */
            tag?: string | null;
            title: string;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Avatar photo
             */
            avatar?: (number | null) | Media;
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            sectionTitle?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base".
 */
export interface KnowledgeBase {
  id: number;
  title: string;
  /**
   * URL path for the article (e.g. kak-sostavlyaetsya-smeta)
   */
  slug: string;
  /**
   * Short description shown in article list
   */
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Show in Knowledge section on home page (recommended articles)
   */
  isFeatured?: boolean | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'knowledge-base';
        value: number | KnowledgeBase;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  description?: T;
  slug?: T;
  content?:
    | T
    | {
        text?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  hasTariffs?: T;
  tariffItems?:
    | T
    | {
        name?: T;
        price?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  order?: T;
  key?: T;
  title?: T;
  duration?: T;
  price?: T;
  slug?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  programSections?:
    | T
    | {
        title?: T;
        content?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showInNav?: T;
  navOrder?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              title?: T;
              subtitle?: T;
              cta?: T;
              ctaLink?: T;
              secondaryCta?: T;
              secondaryCtaLink?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        badge?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        section?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        seoParagraphs?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              title?: T;
              image?: T;
              imageUrl?: T;
              linkUrl?: T;
              linkText?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        serviceList?:
          | T
          | {
              sectionTag?: T;
              sectionTitle?: T;
              sectionSubtitle?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        courseList?:
          | T
          | {
              sectionTag?: T;
              sectionTitle?: T;
              sectionSubtitle?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              sectionTag?: T;
              sectionTitle?: T;
              sectionDescription?: T;
              id?: T;
              blockName?: T;
            };
        principles?:
          | T
          | {
              sectionTag?: T;
              sectionTitle?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        consultationForm?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        advantages?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              ctaText?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              sectionTag?: T;
              sectionTitle?: T;
              sectionDescription?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    ctaText?: T;
                    isFeatured?: T;
                    featuredBadge?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        knowledge?:
          | T
          | {
              tag?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              articlesTitle?: T;
              articleSource?: T;
              manualSlugs?:
                | T
                | {
                    slug?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              tag?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              avatar?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-base_select".
 */
export interface KnowledgeBaseSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  publishedAt?: T;
  isFeatured?: T;
  order?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroCta?: string | null;
  heroBackground?: (number | null) | Media;
  descriptionTitle?: string | null;
  descriptionText?: string | null;
  headerLogo?: (number | null) | Media;
  headerLogoText?: string | null;
  navTariffs?: string | null;
  navKnowledge?: string | null;
  navAbout?: string | null;
  footerTitle?: string | null;
  footerDescription?: string | null;
  /**
   * Заголовок блока навигации в футере
   */
  footerQuickLinksTitle?: string | null;
  footerCopyright?: string | null;
  commonMore?: string | null;
  commonTariffs?: string | null;
  commonRegister?: string | null;
  commonSendRequest?: string | null;
  commonCourseProgram?: string | null;
  commonHome?: string | null;
  commonServices?: string | null;
  commonTraining?: string | null;
  commonContacts?: string | null;
  commonContactUs?: string | null;
  commonPhone?: string | null;
  commonEmail?: string | null;
  commonAddress?: string | null;
  commonWorkingHours?: string | null;
  commonName?: string | null;
  commonMessage?: string | null;
  commonSelectCourse?: string | null;
  commonViewAllServices?: string | null;
  commonOrderCall?: string | null;
  commonGetConsultation?: string | null;
  commonDisclaimer?: string | null;
  commonPhoneError?: string | null;
  commonSuccess?: string | null;
  commonError?: string | null;
  commonSending?: string | null;
  commonSecurityCheck?: string | null;
  commonSecurityError?: string | null;
  commonUnp?: string | null;
  validationNameRequired?: string | null;
  validationMessageRequired?: string | null;
  validationEmailInvalid?: string | null;
  servicesTitle?: string | null;
  servicesSubtitle?: string | null;
  backToServices?: string | null;
  backToService?: string | null;
  notFoundTitle?: string | null;
  notFoundDescription?: string | null;
  trainingSubtitle?: string | null;
  courseDetails?: string | null;
  registrationTitle?: string | null;
  backToCourses?: string | null;
  inDevelopment?: string | null;
  courseProgramTitle?: string | null;
  /**
   * Default meta title for the site
   */
  metaTitle?: string | null;
  /**
   * Default meta description
   */
  metaDescription?: string | null;
  /**
   * Default meta keywords (comma-separated)
   */
  metaKeywords?: string | null;
  /**
   * OG изображение (рекомендуется 1200×630 px). Если не задано — используется фоновое изображение Hero.
   */
  ogImage?: (number | null) | Media;
  /**
   * Allow search engines to index the site
   */
  robotsIndex?: boolean | null;
  /**
   * Allow search engines to follow links
   */
  robotsFollow?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone, email, address — used on main page and in footer. No separate contacts page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  contactPhone?: string | null;
  contactEmail?: string | null;
  contactAddress?: string | null;
  contactWorkingHours?: string | null;
  contactUnp?: string | null;
  /**
   * Заголовок страницы контактов
   */
  contactsTitle?: string | null;
  /**
   * Подзаголовок страницы контактов
   */
  contactsSubtitle?: string | null;
  /**
   * Заголовок блока контактной информации в футере
   */
  contactInfoTitle?: string | null;
  /**
   * Заголовок формы обратной связи
   */
  formTitle?: string | null;
  /**
   * Placeholder для поля телефона в форме
   */
  phonePlaceholder?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroCta?: T;
  heroBackground?: T;
  descriptionTitle?: T;
  descriptionText?: T;
  headerLogo?: T;
  headerLogoText?: T;
  navTariffs?: T;
  navKnowledge?: T;
  navAbout?: T;
  footerTitle?: T;
  footerDescription?: T;
  footerQuickLinksTitle?: T;
  footerCopyright?: T;
  commonMore?: T;
  commonTariffs?: T;
  commonRegister?: T;
  commonSendRequest?: T;
  commonCourseProgram?: T;
  commonHome?: T;
  commonServices?: T;
  commonTraining?: T;
  commonContacts?: T;
  commonContactUs?: T;
  commonPhone?: T;
  commonEmail?: T;
  commonAddress?: T;
  commonWorkingHours?: T;
  commonName?: T;
  commonMessage?: T;
  commonSelectCourse?: T;
  commonViewAllServices?: T;
  commonOrderCall?: T;
  commonGetConsultation?: T;
  commonDisclaimer?: T;
  commonPhoneError?: T;
  commonSuccess?: T;
  commonError?: T;
  commonSending?: T;
  commonSecurityCheck?: T;
  commonSecurityError?: T;
  commonUnp?: T;
  validationNameRequired?: T;
  validationMessageRequired?: T;
  validationEmailInvalid?: T;
  servicesTitle?: T;
  servicesSubtitle?: T;
  backToServices?: T;
  backToService?: T;
  notFoundTitle?: T;
  notFoundDescription?: T;
  trainingSubtitle?: T;
  courseDetails?: T;
  registrationTitle?: T;
  backToCourses?: T;
  inDevelopment?: T;
  courseProgramTitle?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  ogImage?: T;
  robotsIndex?: T;
  robotsFollow?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  contactPhone?: T;
  contactEmail?: T;
  contactAddress?: T;
  contactWorkingHours?: T;
  contactUnp?: T;
  contactsTitle?: T;
  contactsSubtitle?: T;
  contactInfoTitle?: T;
  formTitle?: T;
  phonePlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}