/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    courses: Course;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Unique key for mapping (e.g. estimateService)
   */
  key: string;
  title: string;
  description?: string | null;
  /**
   * URL slug (e.g. smetnoe-obsluzhivanie)
   */
  slug: string;
  content?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  hasTariffs?: boolean | null;
  tariffItems?:
    | {
        name: string;
        price: string;
        description?: string | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Display order on training page (lower = first)
   */
  order?: number | null;
  /**
   * Unique key (e.g. express-course, contract-price)
   */
  key: string;
  title: string;
  duration?: string | null;
  price?: string | null;
  slug: string;
  topics?:
    | {
        topic?: string | null;
        id?: string | null;
      }[]
    | null;
  programSections?:
    | {
        title: string;
        content?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path (e.g. home, services, about-us). Use "home" for the main page.
   */
  slug: string;
  /**
   * Show this page in header/footer navigation
   */
  showInNav?: boolean | null;
  /**
   * Order in navigation (lower = first)
   */
  navOrder?: number | null;
  /**
   * Page meta title
   */
  metaTitle?: string | null;
  /**
   * Page meta description
   */
  metaDescription?: string | null;
  /**
   * Page Open Graph image
   */
  ogImage?: (number | null) | Media;
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            cta?: string | null;
            /**
             * URL for CTA button
             */
            ctaLink?: string | null;
            secondaryCta?: string | null;
            /**
             * URL for secondary button
             */
            secondaryCtaLink?: string | null;
            background?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Max services to show (0 = all)
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceList';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'courseList';
          }
        | {
            /**
             * Form title
             */
            title?: string | null;
            /**
             * Name field label
             */
            nameLabel?: string | null;
            /**
             * Email field label
             */
            emailLabel?: string | null;
            /**
             * Phone field label
             */
            phoneLabel?: string | null;
            /**
             * Message field label
             */
            messageLabel?: string | null;
            /**
             * Submit button text
             */
            submitLabel?: string | null;
            /**
             * Phone input placeholder
             */
            phonePlaceholder?: string | null;
            /**
             * Phone validation error
             */
            phoneError?: string | null;
            /**
             * Success message
             */
            successMessage?: string | null;
            /**
             * Error message
             */
            errorMessage?: string | null;
            /**
             * Sending state message
             */
            sendingMessage?: string | null;
            /**
             * Security check label
             */
            securityCheck?: string | null;
            /**
             * Security error message
             */
            securityError?: string | null;
            validationNameRequired?: string | null;
            validationMessageRequired?: string | null;
            validationEmailInvalid?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            /**
             * Phone number
             */
            contactPhone?: string | null;
            /**
             * Email address
             */
            contactEmail?: string | null;
            /**
             * Physical address
             */
            contactAddress?: string | null;
            /**
             * Working hours
             */
            contactWorkingHours?: string | null;
            /**
             * UNP number
             */
            contactUnp?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  description?: T;
  slug?: T;
  content?:
    | T
    | {
        text?: T;
        id?: T;
      };
  hasTariffs?: T;
  tariffItems?:
    | T
    | {
        name?: T;
        price?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  order?: T;
  key?: T;
  title?: T;
  duration?: T;
  price?: T;
  slug?: T;
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  programSections?:
    | T
    | {
        title?: T;
        content?:
          | T
          | {
              item?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showInNav?: T;
  navOrder?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cta?: T;
              ctaLink?: T;
              secondaryCta?: T;
              secondaryCtaLink?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        section?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        serviceList?:
          | T
          | {
              limit?: T;
              id?: T;
              blockName?: T;
            };
        courseList?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              nameLabel?: T;
              emailLabel?: T;
              phoneLabel?: T;
              messageLabel?: T;
              submitLabel?: T;
              phonePlaceholder?: T;
              phoneError?: T;
              successMessage?: T;
              errorMessage?: T;
              sendingMessage?: T;
              securityCheck?: T;
              securityError?: T;
              validationNameRequired?: T;
              validationMessageRequired?: T;
              validationEmailInvalid?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              contactPhone?: T;
              contactEmail?: T;
              contactAddress?: T;
              contactWorkingHours?: T;
              contactUnp?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroCta?: string | null;
  heroBackground?: (number | null) | Media;
  descriptionTitle?: string | null;
  descriptionText?: string | null;
  headerLogo?: (number | null) | Media;
  headerLogoText?: string | null;
  navHome?: string | null;
  navServices?: string | null;
  navTraining?: string | null;
  navContacts?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  contactAddress?: string | null;
  contactWorkingHours?: string | null;
  contactUnp?: string | null;
  footerTitle?: string | null;
  footerDescription?: string | null;
  footerCopyright?: string | null;
  commonMore?: string | null;
  commonTariffs?: string | null;
  commonRegister?: string | null;
  commonSendRequest?: string | null;
  commonCourseProgram?: string | null;
  commonHome?: string | null;
  commonServices?: string | null;
  commonTraining?: string | null;
  commonContacts?: string | null;
  commonContactUs?: string | null;
  commonPhone?: string | null;
  commonEmail?: string | null;
  commonAddress?: string | null;
  commonWorkingHours?: string | null;
  commonName?: string | null;
  commonMessage?: string | null;
  commonSelectCourse?: string | null;
  commonDisclaimer?: string | null;
  commonPhoneError?: string | null;
  commonSuccess?: string | null;
  commonError?: string | null;
  commonSending?: string | null;
  commonSecurityCheck?: string | null;
  commonSecurityError?: string | null;
  commonUnp?: string | null;
  validationNameRequired?: string | null;
  validationMessageRequired?: string | null;
  validationEmailInvalid?: string | null;
  servicesTitle?: string | null;
  servicesSubtitle?: string | null;
  backToServices?: string | null;
  backToService?: string | null;
  notFoundTitle?: string | null;
  notFoundDescription?: string | null;
  contactsSubtitle?: string | null;
  contactInfoTitle?: string | null;
  formTitle?: string | null;
  phonePlaceholder?: string | null;
  trainingSubtitle?: string | null;
  courseDetails?: string | null;
  registrationTitle?: string | null;
  backToCourses?: string | null;
  inDevelopment?: string | null;
  courseProgramTitle?: string | null;
  /**
   * Default meta title for the site
   */
  metaTitle?: string | null;
  /**
   * Default meta description
   */
  metaDescription?: string | null;
  /**
   * Default meta keywords (comma-separated)
   */
  metaKeywords?: string | null;
  /**
   * Default Open Graph image
   */
  ogImage?: (number | null) | Media;
  /**
   * Allow search engines to index the site
   */
  robotsIndex?: boolean | null;
  /**
   * Allow search engines to follow links
   */
  robotsFollow?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroCta?: T;
  heroBackground?: T;
  descriptionTitle?: T;
  descriptionText?: T;
  headerLogo?: T;
  headerLogoText?: T;
  navHome?: T;
  navServices?: T;
  navTraining?: T;
  navContacts?: T;
  contactPhone?: T;
  contactEmail?: T;
  contactAddress?: T;
  contactWorkingHours?: T;
  contactUnp?: T;
  footerTitle?: T;
  footerDescription?: T;
  footerCopyright?: T;
  commonMore?: T;
  commonTariffs?: T;
  commonRegister?: T;
  commonSendRequest?: T;
  commonCourseProgram?: T;
  commonHome?: T;
  commonServices?: T;
  commonTraining?: T;
  commonContacts?: T;
  commonContactUs?: T;
  commonPhone?: T;
  commonEmail?: T;
  commonAddress?: T;
  commonWorkingHours?: T;
  commonName?: T;
  commonMessage?: T;
  commonSelectCourse?: T;
  commonDisclaimer?: T;
  commonPhoneError?: T;
  commonSuccess?: T;
  commonError?: T;
  commonSending?: T;
  commonSecurityCheck?: T;
  commonSecurityError?: T;
  commonUnp?: T;
  validationNameRequired?: T;
  validationMessageRequired?: T;
  validationEmailInvalid?: T;
  servicesTitle?: T;
  servicesSubtitle?: T;
  backToServices?: T;
  backToService?: T;
  notFoundTitle?: T;
  notFoundDescription?: T;
  contactsSubtitle?: T;
  contactInfoTitle?: T;
  formTitle?: T;
  phonePlaceholder?: T;
  trainingSubtitle?: T;
  courseDetails?: T;
  registrationTitle?: T;
  backToCourses?: T;
  inDevelopment?: T;
  courseProgramTitle?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  ogImage?: T;
  robotsIndex?: T;
  robotsFollow?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}